name = "libcoulcc"
version = "1.0.0"
license = "MIT"
maintainer = "j.forer@posteo.net"
description = "Calculate complex-valued Coulomb and Bessel functions"
keywords = [ "complex", "special", "coulomb", "bessel", "functions" ]

[library]
source-dir = "src"

[dependencies]
stdlib = "*"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

# [dev-dependencies]
# test-drive.git = "https://github.com/fortran-lang/test-drive"
# test-drive.tag = "v0.4.0"

# [[test]]
# name="coulcc-tests"
# source-dir="test"
# main="tester.f"
